### ISSUE TITLE
Help! would you please post the training label text files and validation label text files?

### ISSUE THREAD

**Issue by vollerain** [GeorgeSeif/AlexNet-TensorFlow#1]
help!
would you please post the training label text files and validation label text files?
Thanks a lot!

**Comment by GeorgeSeif** [comment]
Hi @vollerain 

Those files actually come with the PASCAL VOC dataset. They will be named according to the specific object. For example, the file for the object "bicycle" would be called "bicycle_train.txt" for the training labels and "bicycle_val.txt" for the validation labels.

**Comment by vollerain** [comment]
Hi, thanks for your suggestion, and I have successfully run your alexnet code using *_train.txt files in the "main" directory of pascal voc2012 dataset. 
But after a long time training, I find that the prediction accuracy is very low, which is around 30%.
So I just wonder if is your prediction accuracy also so low on this code and dataset? And if is it because pure CNN like alexnet can't handle such kind of complex dataset, and R-CNN is needed instead?
Best regard, and hoping for your answer
